#!/bin/bash



if [ "$1" == "suse" ];then
	if [ "$2" == "--configure" ];then
		if [ "$3" == "Mathematical" ];then
			sudo zypper -n install octave
			sudo zypper -n install jupyter-octave-kernel

			sudo zypper -n install octave-CSXCAD
			sudo zypper -n install pfstools-octave
			sudo zypper -n install python3-octave-kernel
			sudo zypper -n install "octave-forge-*"
			sudo zypper -n install "OpenOctaveMidi*"
			sudo zypper -n install scilab
			sudo zypper -n install CSXCAD-matlab
			sudo zypper -n install jupyter-matlab-kernel
			sudo zypper -n install openEMS-matlab
			sudo zypper -n install python3-jupyter_imatlab_kernel
			sudo zypper -n install texlive-matlab-prettifier

			sudo zypper -n install texlive-matlab-prettifier-doc


		elif [ "$3" == "Finite element analysis" ];then
			sudo zypper -n install netgen
		
		elif [ "$3" == "Electronics" ];then
			sudo zypper -n install "kicad*"
			sudo zypper -n install "fritzing*"
		elif [ "$3" == "cad" ];then
			sudo zypper -n install "freecad"
			sudo zypper -n install "librecad"

		fi
	fi

fi
			
